# Generated by Django 4.2.7 on 2023-11-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='url',
            new_name='image_url',
        ),
    ]
