# Generated by Django 4.2.7 on 2023-11-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(max_length=300, null=True, verbose_name='Profile Image'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
