# Generated by Django 4.2.7 on 2023-11-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_image_delete_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Profile Image'),
        ),
    ]
