# Generated by Django 4.2.7 on 2023-11-28 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pin Title')),
                ('description', models.CharField(max_length=300, verbose_name='Pin Description')),
                ('image', models.CharField(max_length=500, verbose_name='Pin Image URL')),
                ('website', models.CharField(max_length=100, verbose_name='Pin Website')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pins',
                'db_table': 'pins',
            },
        ),
    ]
