# Generated by Django 4.2.7 on 2023-11-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='website',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='pin',
            name='path',
            field=models.CharField(default='website', max_length=100, verbose_name='Pin Path'),
            preserve_default=False,
        ),
    ]
