# Generated by Django 4.2.7 on 2023-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(verbose_name='Email Verification Token')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Email Verification Requests',
                'db_table': 'email_verification_requests',
            },
        ),
        migrations.CreateModel(
            name='ResetPasswordVerication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(verbose_name='Reset Password Token')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Reset Password Requests',
                'db_table': 'reset_password_requests',
            },
        ),
    ]
